name: Test Workflow (from Docker Hub)

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  test:
    permissions:
        contents: read
        packages: read # REQUIRED to pull from GHCR
    runs-on: ubuntu-latest
    env:
      EMAIL_TOKEN: ${{ secrets.EMAIL_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List files (debug)
        run: ls -lh
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Check secret substitution (safe trick)
        run: |
                echo "Docker user is: ${{ secrets.DOCKER_HUB_USER }}-test"

      - name: Docker build
        run: docker build -t pdf-api . 

      - name: Tag image on Docker Hub
        run: docker tag pdf-api ${{ secrets.DOCKER_HUB_USER }}/pdf-api

      - name: Push image to Docker Hub
        run: docker push ${{ secrets.DOCKER_HUB_USER }}/pdf-api

      - name: Run Docker container
        run: |
          docker run -d --name meuapp -p 5000:5000 -e EMAIL_TOKEN=${{ secrets.EMAIL_TOKEN }} ${{ secrets.DOCKER_HUB_USER }}/pdf-api:latest
          sleep 10

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        run: npm run cy:run

      - name: Stop and remove Docker container
        run: |
          docker stop meuapp || true
          docker rm meuapp || true
