name: CI/CD Pipeline

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      EMAIL_TOKEN: ${{ secrets.EMAIL_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_HUB_USER }}/pdf-api:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_HUB_USER }}/pdf-api:latest

      - name: Run container
        run: |
          docker run -d --name meuapp -p 5000:5000 -e EMAIL_TOKEN=$EMAIL_TOKEN ${{ secrets.DOCKER_HUB_USER }}/pdf-api:latest

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        run: npm run cy:run

      - name: Stop and remove container
        run: |
          docker stop meuapp || true
          docker rm meuapp || true
