name: Cypress Tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    needs: build
    env:
      EMAIL_TOKEN: ${{ secrets.EMAIL_TOKEN }}
    steps:
      - name: Load Docker image
        run: docker load -i pdf-api.tar

      - name: Run Docker container
        run: |
          docker run -d --name meuapp -p 3000:3000 -e EMAIL_TOKEN=$EMAIL_TOKEN pdf-api:latest
          sleep 10  # espera o app subir

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        run: npm run cy:run

      - name: Stop Docker container
        run: docker stop meuapp
