name: Test Workflow

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      EMAIL_TOKEN: ${{ secrets.EMAIL_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Load Docker image
        run: docker load -i pdf-api.tar

      - name: Run Docker container
        run: |
          docker run -d --name meuapp -p 5000:5000 -e EMAIL_TOKEN=$EMAIL_TOKEN pdf-api:latest

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        run: npm run cy:run

      - name: Stop and remove Docker container
        run: |
          docker stop meuapp
          docker rm meuapp
