name: Cypress Tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Baixar o código
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Se você gerar a imagem Docker aqui
      - name: Build Docker image
        run: |
          docker build -t pdf-api:latest .

      # 3. Salvar a imagem como .tar
      - name: Save Docker image
        run: docker save -o pdf-api.tar pdf-api:latest

      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: pdf-api.tar
  test:
    runs-on: ubuntu-latest
    needs: build
    env:
      email_token: ${{ secrets.EMAIL_TOKEN }}
    steps:
      # 1. Baixar o código
      - name: Checkout repository
        uses: actions/checkout@v3

  
      - name: Download Docker image artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      # 3. Carregar a imagem Docker do .tar
      - name: Load Docker image
        run: docker load -i pdf-api.tar

      # 4. Rodar o container com variável de ambiente
      - name: Run Docker container
        run: |
          docker run -d --name meuapp -p 5000:5000 -e email_token=$email_token pdf-api:latest
          sleep 10  # espera o app subir

      # 5. Instalar dependências Cypress
      - name: Install dependencies
        run: npm ci

      # 6. Rodar testes Cypress
      - name: Run Cypress tests
        run: npm run cy:run

      # 7. Parar o container
      - name: Stop Docker container
        run: docker stop meuapp
