name: Cypress Tests
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest
    env:
      EMAIL_TOKEN: ${{ secrets.EMAIL_TOKEN }}
    steps:
    # 1. Baixar o código
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Load Docker image
      run: docker load -i pdf-api.tar
      shell: bash

    # 3. Rodar o container com variável de ambiente
    - name: Run Docker container
      run: |
        docker run -d --name meuapp -p 5000:5000 -e EMAIL_TOKEN=$EMAIL_TOKEN pdf-api:latest
        sleep 10  # espera o app iniciar

    # 4. Instalar dependências do Cypress
    - name: Install dependencies
      run: npm ci

    # 5. Rodar testes Cypress
    - name: Run Cypress tests
      run: npm run cy:run

    # 6. Parar o container
    - name: Stop Docker container
      run: docker stop meuapp
