name: Run Cypress Tests on PDF API Container

on:
  workflow_dispatch:
    inputs:
      email:
        description: 'Email used to the test, *please always use yopmail emails for testing*'
        required: true
        default: 'pdf_testmail@yopmail.com'
        type: string
      pdf_name: 
        description: 'name of the attached file'
        required: true
        default: test_pdf
        type: string
      
      
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      
          
      - name: Run Docker container
        run: |
          docker compose up -d

      - name: Install Cypress dependencies
        run: npm ci

      - name: Run Cypress tests
        
        run: |
          echo "ðŸ§ª Running Cypress tests against http://localhost:5000"
          npx cypress run --env url=http://localhost:5000/pdf,file_name=${{ inputs.pdf_name }},email=${{ inputs.email }},yopmail=https://yopmail.com/ -- --enable-unsafe-swiftshader
          
      - name: Dump docker logs on failure
        uses: jwalton/gh-docker-logs@v2
      
      - name: Stop and clean up
        run: |
          docker compose down --rmi all || true
