name: Cypress tests

on:
  workflow_dispatch:
    inputs:
      email:
        description: 'Email usado para receber o Pdf da API'
        required: true
        default: pdf_testmail@yopmail.com
        type: string
      pdf_name:
        description: 'Nome do arquivo pdf gerado'
        required: true
        default: test_pdf
        type: string


jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }} 
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Run Docker container
        run: |
          docker compose up -d

      - name: Installl Cypress dependencies
        run: npm ci

      - name: Run Cypress tests 
        run: |
          echo "Running Cypress tests on docker container"
          npm run cy:run
          
      - name: Uploading artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: report_tests
          path: mochawesome-report
          retention-days: 30

      - name: Stop and clean up
        run: | 
          docker compose down --rmi all || true
          
